# Generated by Django 4.1.1 on 2022-09-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
    ]
